classdef SiSaMode < handle
    %SISAMODE Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        p             % parent, generic UI object
        h = struct(); % GUI handles
        
        fit_params;
        fit_params_err;
        fit_chisq;
        est_params;
        last_fitted;
        
        overlays = {};  % 1 is always the automatically generated overlay,
                        % additional overlays can be added
        current_ov = 1;
        overlay_data;
        disp_ov = false;
        selection_props;
        
        cancel_f = false;
        hold_f = false;
        model = '1. A*(exp(-t/t1)-exp(-t/t2))+offset';      % fit model, should be global  
        
        channel_width = 20/1000;   % needs UI element
        t_offset = 25;   % excitation is over after t_offset channels after 
                         % maximum counts were reached - needs UI element
        t_zero = 0;      % channel in which the maximum of the excitation was reached
        
        disp_fit_params = 0;
        l_min; % maximum of the current parameter over all data points
        l_max; % minimum of the current parameter over all data points
        use_user_legend = false;
        user_l_min;
        user_l_max;
        
        fitted = false;
        cmap = 'summer';
        
        fix = {};
        gstart = [0 0 0 0];
        use_gstart = [0 0 0 0]';
        models = containers.Map(...
                 {'1. A*(exp(-t/t1)-exp(-t/t2))+offset'...
                  '2. A*(exp(-t/t1)-exp(-t/t2))+B*exp(-t/t2)+offset'...
                  '3. A*(exp(-t/t1)-exp(-t/t2))+B*exp(-t/t1)+offset'...
                  '4. A*(exp(-t/t1)+B*exp(-t/t2)+offset'...
                 },...
                 {...
                    % function, lower bounds, upper bounds, names of arguments
                    {@(A, t1, t2, offset, t) A*(exp(-t/t1)-exp(-t/t2))+offset, [0 0 0 0], [inf inf inf inf], {'A', 't1', 't2', 'offset'} }...
                    {@(A, t1, t2, B, offset, t) A*(exp(-t/t1)-exp(-t/t2))+B*exp(-t/t2)+offset, [0 0 0 0 0], [inf inf inf inf inf], {'A', 't1', 't2', 'B', 'offset'} }...
                    {@(A, t1, t2, B, offset, t) A*(exp(-t/t1)-exp(-t/t2))+B*exp(-t/t1)+offset, [0 0 0 0 0], [inf inf inf inf inf], {'A', 't1', 't2', 'B', 'offset'} }...
                    {@(A, t1, t2, B, offset, t) A*exp(-t/t1)+B*exp(-t/t2)+offset, [0 0 0 0 0], [inf inf inf inf inf], {'A', 't1', 't2', 'B', 'offset'} }...
                  })
                    
        models_latex = containers.Map(...
                 {'1. A*(exp(-t/t1)-exp(-t/t2))+offset'...
                  '2. A*(exp(-t/t1)-exp(-t/t2))+B*exp(-t/t2)+offset'...
                  '3. A*(exp(-t/t1)-exp(-t/t2))+B*exp(-t/t1)+offset'...
                  '4. A*(exp(-t/t1)+B*exp(-t/t2)+offset'...
                 },...
                 {...
                 { '$$f(t) = A\cdot \left[\exp \left(\frac{t}{\tau_1}\right) - \exp \left(\frac{t}{\tau_2}\right) \right] + o$$', {'A', '\tau_1', '\tau_2', 'o'}, {'Counts', '$$\mu$$s', '$$\mu$$s', 'Counts'} }...
                 { '$$f(t) = A\cdot \left[\exp \left(\frac{t}{\tau_1}\right) - \exp \left(\frac{t}{\tau_2}\right) \right] + B \cdot \exp\left(\frac{t}{\tau_2}\right) + o$$', {'A', '\tau_1', '\tau_2', 'B', 'o'}, {'Counts', '$$\mu$$s', '$$\mu$$s', 'Counts', 'Counts'} }...
                 { '$$f(t) = A\cdot \left[\exp \left(\frac{t}{\tau_1}\right) - \exp \left(\frac{t}{\tau_2}\right) \right] + B \cdot \exp\left(\frac{t}{\tau_1}\right) + o$$', {'A', '\tau_1', '\tau_2', 'B', 'o'}, {'Counts', '$$\mu$$s', '$$\mu$$s', 'Counts', 'Counts'} }...
                 { '$$f(t) = A\cdot \exp \left(\frac{t}{\tau_1}\right) + B\cdot \exp \left(\frac{t}{\tau_2}\right) + o$$', {'A', '\tau_1', '\tau_2', 'B', 'o'}, {'Counts', '$$\mu$$s', '$$\mu$$s', 'Counts', 'Counts'} }...
                 })
    end
    
    methods
        function this = SiSaMode(parent)
            this.p = parent;
            
            this.h.parent = parent.h.modepanel;
            
            this.h.sisamode = uitab(this.h.parent);
            
            this.h.plotpanel = uipanel(this.h.sisamode);
                        this.h.axes = axes('parent', this.h.plotpanel);
                        this.h.legend = axes('parent', this.h.plotpanel);
                        this.h.tick_min = uicontrol(this.h.plotpanel);
                        this.h.tick_max = uicontrol(this.h.plotpanel);
                        this.h.plttxt = uicontrol(this.h.plotpanel);
                        this.h.zslider = uicontrol(this.h.plotpanel);
                        this.h.zbox = uicontrol(this.h.plotpanel);
                        this.h.saslider = uicontrol(this.h.plotpanel);
                        this.h.sabox = uicontrol(this.h.plotpanel);
                        this.h.param = uicontrol(this.h.plotpanel);
                        this.h.fit_est = uibuttongroup(this.h.plotpanel);
                            this.h.fit_par = uicontrol();
                            this.h.est_par = uicontrol();
                        this.h.d1_select = uicontrol(this.h.plotpanel);
                        this.h.d2_select = uicontrol(this.h.plotpanel);
                        this.h.d3_select = uicontrol(this.h.plotpanel);
                        this.h.d4_select = uicontrol(this.h.plotpanel);

                    this.h.tabs = uitabgroup(this.h.sisamode);
                        this.h.fit_tab = uitab(this.h.tabs);
                            this.h.fitpanel = uipanel(this.h.fit_tab);
                                this.h.fittxt = uicontrol(this.h.fitpanel);
                                this.h.drpd = uicontrol(this.h.fitpanel);
                                this.h.bounds = uipanel(this.h.fitpanel);
                                    this.h.bounds_txt1 = uicontrol(this.h.bounds);
                                    this.h.bounds_txt2 = uicontrol(this.h.bounds);
                                    this.h.gstart_text = uicontrol(this.h.bounds);
                                    this.h.fix_text = uicontrol(this.h.bounds);
                                    this.h.glob_text = uicontrol(this.h.bounds);
                            this.h.parallel = uicontrol(this.h.fit_tab);
                            this.h.fit = uicontrol(this.h.fit_tab);
                            this.h.hold = uicontrol(this.h.fit_tab);
                            this.h.ov_controls = uipanel(this.h.fit_tab);
                                this.h.ov_disp = uicontrol(this.h.ov_controls);
                                this.h.ov_buttongroup = uibuttongroup(this.h.ov_controls);
                                    this.h.ov_radiobtns = {uicontrol(this.h.ov_buttongroup)};
                                    this.h.ov_drpd = uicontrol(this.h.ov_controls);
                                    this.h.ov_rel = uicontrol(this.h.ov_controls);
                                    this.h.ov_val = uicontrol(this.h.ov_controls);
                                    this.h.ov_add_from_auto = uicontrol(this.h.ov_controls);
                                    this.h.add_overlay = {};

                        this.h.sel_tab = uitab(this.h.tabs);
                            this.h.sel_controls = uipanel(this.h.sel_tab);
                                this.h.sel_btn_plot = uicontrol(this.h.sel_controls);

                            this.h.sel_values = uipanel(this.h.sel_tab);

                        this.h.pres_tab = uitab(this.h.tabs);
                            this.h.savefig = uicontrol(this.h.pres_tab);
                            this.h.prevfig = uicontrol(this.h.pres_tab);
                            this.h.pres_controls = uipanel(this.h.pres_tab);
                                this.h.colormap_drpd_text = uicontrol(this.h.pres_controls);
                                this.h.colormap_drpd = uicontrol(this.h.pres_controls);
                                this.h.scale_x_text = uicontrol(this.h.pres_controls);
                                this.h.scale_x = uicontrol(this.h.pres_controls);
                                this.h.scale_y_text = uicontrol(this.h.pres_controls);
                                this.h.scale_y = uicontrol(this.h.pres_controls);
                                
                                
            set(this.h.sisamode, 'title', 'SiSa',...
                                 'SizeChangedFcn', @this.resize);
                %% Plot
            set(this.h.plotpanel, 'units', 'pixels',...
                                'position', [270 5 500 500],...
                                'bordertype', 'line',...
                                'highlightcolor', [.7 .7 .7],...
                                'BackgroundColor', [.85 .85 .85]);
            
            set(this.h.axes, 'units', 'pixels',...
                           'position', [40 60 380 390],...
                           'Color', get(this.h.plotpanel, 'BackgroundColor'),...
                           'xtick', [], 'ytick', [],...
                           'XColor', get(this.h.plotpanel, 'BackgroundColor'),...
                           'YColor', get(this.h.plotpanel, 'BackgroundColor'),...
                           'ButtonDownFcn', @this.aplot_click_cb);
                       
            set(this.h.legend, 'units', 'pixels',...
                             'position', [40 12 400 20],...
                             'xtick', [], 'ytick', [],...
                             'XColor', get(this.h.plotpanel, 'BackgroundColor'),...
                             'YColor', get(this.h.plotpanel, 'BackgroundColor'),...
                             'visible', 'off');
                                     
            set(this.h.plttxt, 'units', 'pixels',...
                             'style', 'text',...
                             'string', 'Parameter:',...
                             'position', [50 452 100 20],...
                             'HorizontalAlignment', 'left',...
                             'BackgroundColor', get(this.h.plotpanel, 'BackgroundColor'),...
                             'FontSize', 9,...
                             'visible', 'off');
                                                       
            set(this.h.zslider, 'units', 'pixels',...
                              'style', 'slider',...
                              'position', [460 85 20 340],...
                              'value', 1,...
                              'visible', 'off',...
                              'callback', @this.set_d3_cb,...
                              'BackgroundColor', [1 1 1]);
                           
            set(this.h.zbox, 'units', 'pixels',...
                           'style', 'edit',...
                           'string', '1',...
                           'position', [460 430 20, 20],...
                           'callback', @this.set_d3_cb,...
                           'visible', 'off',...
                           'BackgroundColor', [1 1 1]);
            
            set(this.h.saslider, 'units', 'pixels',...
                               'style', 'slider',...
                               'position', [490 85 20 340],... 
                               'value', 1,...
                               'visible', 'off',...
                               'BackgroundColor', [1 1 1],...
                               'ForegroundColor', [0 0 0],...
                               'callback', @this.set_d4_cb);

            set(this.h.sabox, 'units', 'pixels',...
                            'style', 'edit',...
                            'string', '1',...
                            'position', [490 460 20 20],...
                            'callback', @this.set_d4_cb,...
                            'visible', 'off',...
                            'BackgroundColor', [1 1 1]);

            set(this.h.param, 'units', 'pixels',...
                            'style', 'popupmenu',...
                            'string', {},...
                            'position', [120 470 80 20],...
                            'FontSize', 9,...
                            'visible', 'off',...
                            'callback', @this.set_param_cb,...
                            'BackgroundColor', [1 1 1]);
                        
            set(this.h.tick_min, 'units', 'pixels',...
                               'style', 'edit',...
                               'visible', 'off',...
                               'FontSize', 9,...
                               'string', '1',...
                               'horizontalAlignment', 'left',...
                               'callback', @this.set_tick_cb,...
                               'position', [40 34 65 17]);
                           
            set(this.h.tick_max, 'units', 'pixels',...
                               'style', 'edit',...
                               'visible', 'off',...
                               'FontSize', 9,...
                               'string', '100',...
                               'horizontalAlignment', 'right',...
                               'callback', @this.set_tick_cb,...
                               'position', [405 34 65 17]);  
                           
            set(this.h.est_par, 'units', 'pixels',...
                              'style', 'radiobutton',...
                              'visible', 'on',...
                              'FontSize', 9,...
                              'BackgroundColor', get(this.h.plotpanel, 'BackgroundColor'),...
                              'string', 'abgeschätzt',...
                              'horizontalAlignment', 'left',...
                              'position', [10 1 100 17],...
                              'parent', this.h.fit_est);
                           
            set(this.h.fit_par, 'units', 'pixels',...
                              'style', 'radiobutton',...
                              'visible', 'on',...
                              'FontSize', 9,...
                              'BackgroundColor', get(this.h.plotpanel, 'BackgroundColor'),...
                              'string', 'gefittet',...
                              'horizontalAlignment', 'left',...
                              'position', [115 1 60 17],...
                              'parent', this.h.fit_est,...
                              'visible', 'off');
                          
            set(this.h.fit_est, 'units', 'pixels',...
                              'BackgroundColor', get(this.h.plotpanel, 'BackgroundColor'),...
                              'BorderType', 'none',...
                              'SelectionChangeFcn', @this.change_par_source_cb,...
                              'position', [220 445 200 21],...
                              'visible', 'off');          
                          
            set(this.h.d1_select, 'units', 'pixels',...
                                'style', 'popupmenu',...
                                'value', 1,...
                                'tag', '1',...
                                'visible', 'off',...
                                'callback', @this.set_dim_cb,...
                                'position', [385 40 30 17],...
                                'BackgroundColor', [1 1 1]);
%                                 'string', this.dimnames,...
                            
            set(this.h.d2_select, 'units', 'pixels',...
                                'style', 'popupmenu',...
                                'value', 2,...
                                'visible', 'off',...
                                'tag', '2',...
                                'callback', @this.set_dim_cb,...
                                'position', [5 300 30 17],...
                                'BackgroundColor', [1 1 1]);
%                                 'string', this.dimnames,...


            set(this.h.d3_select, 'units', 'pixels',...
                                'style', 'popupmenu',...
                                'value', 3,...
                                'visible', 'off',...
                                'tag', '3',...
                                'callback', @this.set_dim_cb,...
                                'position', [465 520 30 17],...
                                'BackgroundColor', [1 1 1]);
%                                 'string', this.dimnames,...

                            
            set(this.h.d4_select, 'units', 'pixels',...
                                'style', 'popupmenu',...
                                'value', 4,...
                                'visible', 'off',...
                                'tag', '4',...
                                'callback', @this.set_dim_cb,...
                                'position', [505 520 30 17],...
                                'BackgroundColor', [1 1 1]);
%                                 'string', this.dimnames,...

                            
            %% tabs for switching selection modes
            set(this.h.tabs, 'units', 'pixels',...
                             'position', [10 5 250 550],...
                             'visible', 'off');
                           
            %% Fitten
            set(this.h.fit_tab, 'Title', 'Fitten');
            
            set(this.h.fit,  'units', 'pixels',...
                           'style', 'push',...
                           'position', [2 2 80 28],...
                           'string', 'global Fitten',...
                           'callback', @this.fit_all_cb);
                       
            set(this.h.hold, 'units', 'pixels',...
                           'style', 'push',...
                           'position', [250-80-5 2 80 28],...
                           'string', 'Fit anhalten',...
                           'visible', 'off',...
                           'callback', @this.hold_fit_cb);
                       
            set(this.h.parallel, 'units', 'pixels',...
                            'style', 'checkbox',...
                            'string', 'parallel Fitten? (keine Interaktivität!)',...
                            'tooltipString', 'Dauert am Anfang ein bisschen. Keine Fortschrittsanzeige!',...
                            'position', [2 35 200 15]);
                        
            if isdeployed()
                set(this.h.parallel, 'visible', 'off');
            end
                        
            %% overlay control
            set(this.h.ov_controls, 'units', 'pixels',...
                                    'position', [2 260 243 200],...
                                    'bordertype', 'line',...
                                    'highlightcolor', [.7 .7 .7]);
                              
            set(this.h.ov_buttongroup, 'units', 'pixels',...
                                       'bordertype', 'none',...
                                       'position', [2 2 237 170]);

            set(this.h.ov_disp, 'units', 'pixels',...
                              'style', 'checkbox',...
                              'position', [15 175 150 20],...
                              'string', 'Overlay anzeigen',...
                              'callback', @this.disp_ov_cb);
                              
            set(this.h.ov_buttongroup, 'SelectionChangedFcn', @this.set_current_ov_cb);
            
            set(this.h.ov_radiobtns{1}, 'units', 'pixels',...
                                   'style', 'radiobutton',...
                                   'tag', '1',...
                                   'position', [15 135 15 15]);
                               
            set(this.h.ov_add_from_auto, 'units', 'pixels',...
                                       'style', 'pushbutton',...
                                       'string', '+',...
                                       'position', [190 134 20 20],...
                                       'callback', {@this.add_ov_cb, 1});
                                           
            set(this.h.ov_drpd, 'units', 'pixels',...
                              'style', 'popupmenu',...
                              'position', [35 125 60 30],...
                              'string', {''},...
                              'callback', @this.change_overlay_cond_cb,...
                              'BackgroundColor', [1 1 1]);
                         
            set(this.h.ov_rel, 'units', 'pixels',...
                             'style', 'popupmenu',...
                             'position', [96 125 30 30],...
                             'string', {'<', '>'},...
                             'value', 2,...
                             'callback', @this.change_overlay_cond_cb,...
                             'BackgroundColor', [1 1 1]);
            
            set(this.h.ov_val, 'units', 'pixels',...
                             'style', 'edit',...
                             'position', [127 133 60 22],...
                             'string', '',...
                             'callback', @this.change_overlay_cond_cb,...
                             'BackgroundColor', [1 1 1]); 
                         
            %% Fit-Panel:
            set(this.h.fitpanel, 'units', 'pixels',...
                               'position', [2 55 243 260],...
                               'title', 'Fit-Optionen',...
                               'bordertype', 'line',...
                               'highlightcolor', [.7 .7 .7],...
                               'FontSize', 9);

            % select fit model
            set(this.h.fittxt, 'units', 'pixels',...
                             'style', 'text',...
                             'position', [15 220 50 15],...
                             'HorizontalAlignment', 'left',...
                             'string', 'Fitmodell:');

            set(this.h.drpd, 'units', 'pixels',...
                           'style', 'popupmenu',...
                           'string', keys(this.models),...
                           'value', 1,...
                           'position', [15 205 220 15],...
                           'callback', @this.set_model_cb,...
                           'BackgroundColor', [1 1 1]);
                       
            set(this.h.bounds, 'units', 'pixels',...
                             'position', [2 10 237 180],...
                             'title', 'Fitparameter',...
                             'bordertype', 'line',...
                             'highlightcolor', [.7 .7 .7],...
                             'FontSize', 9);
                          
            set(this.h.bounds_txt1, 'units', 'pixels',...
                                  'position', [40 145 50 15],...
                                  'style', 'text',...
                                  'string', 'untere',...
                                  'horizontalAlignment', 'left');
                              
            set(this.h.bounds_txt2, 'units', 'pixels',...
                                  'position', [95 145 50 15],...
                                  'style', 'text',...
                                  'string', 'obere',...
                                  'horizontalAlignment', 'left');
                              
            set(this.h.gstart_text, 'units', 'pixels',...
                             'position', [150 145 50 15],...
                             'style', 'text',...
                             'string', 'Start',...
                             'tooltipString', 'globale Startwerte',...
                             'horizontalAlignment', 'left');
                            
            set(this.h.fix_text, 'units', 'pixels',...
                               'position', [201 145 20 15],...
                               'style', 'text',...
                               'string', 'f',...
                               'tooltipString', 'Parameter fixieren',...
                               'horizontalAlignment', 'left');
                            
            set(this.h.glob_text, 'units', 'pixels',...
                               'position', [218 145 20 15],...
                               'style', 'text',...
                               'string', 'g',...
                               'tooltipString', 'Startwerte globalisieren',...
                               'horizontalAlignment', 'left');
                            
            this.h.lb = cell(1, 1);
            this.h.ub = cell(1, 1);
            this.h.st = cell(1, 1);
            this.h.fix = cell(1, 1);
            this.h.n = cell(1, 1);
            this.h.gst = cell(1, 1);

            %% interpretation
            set(this.h.sel_tab, 'Title', 'Auswertung');
            
            set(this.h.sel_controls, 'units', 'pixels',...
                                   'position', [2 360 243 100])
      
            set(this.h.sel_btn_plot, 'units', 'pixels',...
                             'style', 'push',...
                             'position', [15 50 50 20],...
                             'string', 'Plotten',...
                             'callback', @this.plot_group);

            % info about the selected data
            set(this.h.sel_values, 'units', 'pixels',...
                                   'bordertype', 'line',...
                                   'highlightcolor', [.7 .7 .7],...
                                   'position', [2 100 243 250])  
            
            this.h.mean = cell(1, 1);
            this.h.var = cell(1, 1);
            this.h.par = cell(1, 1);
            
            %% presentation
            set(this.h.pres_tab, 'Title', 'Darstellung');
            
            set(this.h.pres_controls, 'units', 'pixels',...
                                    'position', [2 50 243 250])
                               
            set(this.h.savefig, 'units', 'pixels',...
                              'style', 'push',...
                              'position', [2 2 80 28],...
                              'string', 'Plot speichern',...
                              'callback', @this.save_fig);
                          
            set(this.h.prevfig, 'units', 'pixels',...
                              'style', 'push',...
                              'position', [92 2 80 28],...
                              'string', 'Vorschau',...
                              'callback', @this.generate_export_fig_cb);
                          
            set(this.h.colormap_drpd_text, 'units', 'pixels',...
                                         'style', 'text',...
                                         'string', 'Colormap:',...
                                         'horizontalAlignment', 'left',...
                                         'position', [10, 142, 50, 25]);
                          
            set(this.h.colormap_drpd, 'units', 'pixels',...
                                    'style', 'popupmenu',...
                                    'position', [70, 160, 80, 10],...
                                    'string', {'parula', 'jet', 'hsv',...
                                               'hot', 'cool', 'spring',...
                                               'summer', 'autumn', 'winter',...
                                               'gray', 'bone', 'copper',...
                                               'pink'},...
                                    'value', 7,...
                                    'callback', @this.set_cmap_cb);
            
            set(this.h.scale_x_text, 'units', 'pixels',...
                                   'style', 'text',...
                                   'string', 'mm/px X:',...
                                   'horizontalAlignment', 'left',...
                                   'position', [10, 112, 80, 25]);
                                     
            set(this.h.scale_x, 'units', 'pixels',...
                              'style', 'edit',...
                              'callback', @this.set_scale_cb,...
                              'position', [70, 120, 80, 20]);
            
            set(this.h.scale_y_text, 'units', 'pixels',...
                                   'style', 'text',...
                                   'string', 'mm/px Y:',...
                                   'horizontalAlignment', 'left',...
                                   'position', [10, 82, 80, 25]);

            set(this.h.scale_y, 'units', 'pixels',...
                              'style', 'edit',...
                              'callback', @this.set_scale_cb,...
                              'position', [70, 90, 80, 20]);      
            
        end
    end
    
    methods (Access = private)
        function resize(this, varargin)
            mP = get(this.h.parent, 'Position');

            mP(4) = mP(4)-25;
            pP = get(this.h.plotpanel, 'Position');
            pP(3:4) = [(mP(3)-pP(1))-10 (mP(4)-pP(2))-10];
            set(this.h.plotpanel, 'Position', pP);

            aP = get(this.h.axes, 'Position');
            aP(3:4) = [(pP(3)-aP(1))-80 (pP(4)-aP(2))-50];
            set(this.h.axes, 'Position', aP);

            tmp = get(this.h.d2_select, 'Position');
            tmp(2) = aP(2) + aP(4)/2;
            set(this.h.d2_select, 'Position', tmp);

            tmp = get(this.h.d1_select, 'Position');
            tmp(1) = aP(1) + aP(3)/2;
            set(this.h.d1_select, 'Position', tmp);

            tmp = get(this.h.d3_select, 'Position');
            tmp(1) = aP(1) + aP(3) + 5;
            tmp(2) = aP(2) + aP(4) - 16;
            set(this.h.d3_select, 'Position', tmp);

            tmp(1) = aP(1) + aP(3) + 40;
            set(this.h.d4_select, 'Position', tmp);

            tmp = get(this.h.legend, 'position');
            tmp(3) = aP(3);
            set(this.h.legend, 'position', tmp);

            tmp = get(this.h.tick_max, 'position');
            tmp(1) = aP(3) + aP(1) - tmp(3);
            set(this.h.tick_max, 'position', tmp);

            tmp = get(this.h.plttxt, 'position');
            tmp(2) = aP(2)+aP(4)+2;
            set(this.h.plttxt, 'position', tmp);

            tmp = get(this.h.param, 'position');
            tmp(2) = aP(2)+aP(4)+6;
            set(this.h.param, 'position', tmp);

            tmp = get(this.h.fit_est, 'position');
            tmp(2) = aP(2)+aP(4) + 6;
            set(this.h.fit_est, 'position', tmp);

            tmp = get(this.h.zslider, 'position');
            tmp(1) = aP(1) + aP(3) + 15;
            tmp(4) = aP(4) - 50;
            set(this.h.zslider, 'position', tmp);

            tmp(1) = tmp(1) + 25;
            set(this.h.saslider, 'position', tmp);

            tmp = get(this.h.zbox, 'position');
            tmp(1) = aP(1) + aP(3) + 15;
            tmp(2) = aP(1) + 20;
            set(this.h.zbox, 'position', tmp);

            tmp(1) = tmp(1) + 25;
            set(this.h.sabox, 'position', tmp);

            tP = get(this.h.tabs, 'Position');
            tP(4) = pP(4);
            set(this.h.tabs, 'Position', tP);

            tmp = get(this.h.ov_controls, 'Position');
            tmp(2) = tP(4) - tmp(4) - 40;
            set(this.h.ov_controls, 'Position', tmp);
            set(this.h.sel_controls, 'Position', tmp);
        end
    end
end
